spring.profiles.active: develop
server:
  port: 8090
---
spring.config.activate.on-profile: develop
spring:
  jpa:
    show_sql: false
    database: H2
    hibernate:
      ddl-auto: none
  datasource:
    url: jdbc:h2:mem:testdb;DB_CLOSE_ON_EXIT=FALSE;IGNORECASE=TRUE
  sql:
    init:
      mode: always
stripe.simulator.charges-uri: https://sandbox.playtomic.io/v1/stripe-simulator/charges
stripe.simulator.refunds-uri: https://sandbox.playtomic.io/v1/stripe-simulator/payments/{payment_id}/refunds
---
spring.config.activate.on-profile: test
spring:
  jpa:
    show_sql: false
    database: H2
  datasource:
    url: jdbc:h2:mem:testdb;DB_CLOSE_ON_EXIT=FALSE;IGNORECASE=TRUE
  sql:
    init:
      mode: never
stripe.simulator.charges-uri: http://localhost:9999
stripe.simulator.refunds-uri: http://localhost:9999